"""add plugin states

Revision ID: 07379a96de6a
Revises: d9067bce9b24
Create Date: 2025-05-28 12:56:13.820905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "07379a96de6a"
down_revision: Union[str, None] = "d9067bce9b24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plugins", sa.Column("state", sa.String(length=50), nullable=False))
    op.drop_column("plugins", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plugins",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("plugins", "state")
    # ### end Alembic commands ###
