"""add identifier to workspace

Revision ID: 2550d4723c64
Revises: ed70d724812c
Create Date: 2025-01-27 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2550d4723c64"
down_revision: Union[str, None] = "9849583adcd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspaces", sa.Column("identifier", sa.String(length=100), nullable=True)
    )
    op.create_unique_constraint(
        "uq_workspaces_identifier", "workspaces", ["identifier"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_workspaces_identifier", "workspaces", type_="unique")
    op.drop_column("workspaces", "identifier")
    # ### end Alembic commands ###
