"""create projects

Revision ID: e40d9faf9872
Revises: aeca0aab0e4d
Create Date: 2025-05-06 10:05:15.045646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e40d9faf9872"
down_revision: Union[str, None] = "aeca0aab0e4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("system_prompt", sa.String(), nullable=True),
        sa.Column("logo", sa.String(), nullable=True),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("ingest_settings", sa.JSON(), nullable=True),
        sa.Column("llm_provider", sa.String(), nullable=False),
        sa.Column("llm", sa.String(), nullable=False),
        sa.Column("embed_model", sa.String(), nullable=False),
    ),

    # ### end Alembic commands ###
    sa.ForeignKeyConstraint(
        ["workspace_id"],
        ["workspaces.id"],
    ),


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects")
    # ### end Alembic commands ###
