# Global Configurations
global:
  scrape_interval: 5s
  evaluation_interval: 5s

# Targets to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['docker.for.mac.localhost:9090']

  - job_name: 'cloud-portal'
    static_configs:
      - targets: ['docker.for.mac.localhost:3000']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
